### ISSUE TITLE
Add gir1.2-gtk-3.0

### ISSUE THREAD

**Issue by neobrain** [FEX-Emu/RootFS#10]
This adds less than 2 MiB of data and enables use of [steam-runtime-launch-options](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md?ref_type=heads#using-steam-runtime-launch-options), a useful debugging tool bundled with the Steam Runtime.

CC @Sonicadvance1

**Comment by teohhanhui** [comment]
~~@Sonicadvance1 391d2b7 missed Fedora 40... :see_no_evil:~~ Oh, never mind, it's installed by default.
